In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('web-scrape/baringo_weather_data_2010_2020.csv')

df.head()

,time,temperature,dew_point,humidity,wind_speed,pressure,precipitation,temperature_raw,dew_point_raw,humidity_raw,wind_speed_raw,pressure_raw,precipitation_raw
0,2010-01-01,18.0,14.0,85.0,5.0,29.91,23.0,18 | 64.4,14 | 57.2,85,5 | 3.11,29.91 | 1013,23.0 | 0.91
1,2010-01-02,18.0,16.0,89.0,6.0,29.94,28.8,18 | 64.4,16 | 60.8,89,6 | 3.73,29.94 | 1014,28.8 | 1.13
2,2010-01-03,18.0,14.0,82.0,10.0,29.94,2.5,18 | 64.4,14 | 57.2,82,10 | 6.21,29.94 | 1014,2.5 | 0.1
3,2010-01-04,18.0,13.0,76.0,9.0,29.94,1.7,18 | 64.4,13 | 55.4,76,9 | 5.59,29.94 | 1014,1.7 | 0.07
4,2010-01-05,19.0,12.0,69.0,10.0,29.91,1.3,19 | 66.2,12 | 53.6,69,10 | 6.21,29.91 | 1013,1.3 | 0.05

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4150 entries, 0 to 4149
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time               4018 non-null   object
 1   temperature        4018 non-null   float64
 2   dew_point          4018 non-null   float64
 3   humidity           4018 non-null   float64
 4   wind_speed         4018 non-null   float64
 5   pressure           4018 non-null   float64
 6   precipitation      4018 non-null   float64
 7   temperature_raw    4150 non-null   object
 8   dew_point_raw      4150 non-null   object
 9   humidity_raw       4150 non-null   object
 10  wind_speed_raw     4150 non-null   object
 11  pressure_raw       4150 non-null   object
 12  precipitation_raw  4150 non-null   object
dtypes: float64(6), object(7)
memory usage: 421.6+ KB

In [4]:
# Change the data type of the time column to be of datetime
df['time'] = pd.to_datetime(df['time'], format='%Y-%m-%d', errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4150 entries, 0 to 4149
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   time               4018 non-null   datetime64[ns]
 1   temperature        4018 non-null   float64
 2   dew_point          4018 non-null   float64
 3   humidity           4018 non-null   float64
 4   wind_speed         4018 non-null   float64
 5   pressure           4018 non-null   float64
 6   precipitation      4018 non-null   float64
 7   temperature_raw    4150 non-null   object
 8   dew_point_raw      4150 non-null   object
 9   humidity_raw       4150 non-null   object
 10  wind_speed_raw     4150 non-null   object
 11  pressure_raw       4150 non-null   object
 12  precipitation_raw  4150 non-null   object
dtypes: datetime64[ns](1), float64(6), object(6)
memory usage: 421.6+ KB

In [5]:
# Check the number of missing values
df.isna().sum()

time                 132
temperature          132
dew_point            132
humidity             132
wind_speed           132
pressure             132
precipitation        132
temperature_raw        0
dew_point_raw          0
humidity_raw           0
wind_speed_raw         0
pressure_raw           0
precipitation_raw      0
dtype: int64

In [8]:
# Remove the rows that had missing values
df = df.dropna()

df.isna().sum()

time                 0
temperature          0
dew_point            0
humidity             0
wind_speed           0
pressure             0
precipitation        0
temperature_raw      0
dew_point_raw        0
humidity_raw         0
wind_speed_raw       0
pressure_raw         0
precipitation_raw    0
dtype: int64

In [9]:
# Remove the raw columns
columns = ['temperature_raw', 'dew_point_raw', 'humidity_raw', 'wind_speed_raw', 
           'pressure_raw', 'precipitation_raw']

df = df.drop(columns, axis=1)

df.head()

,time,temperature,dew_point,humidity,wind_speed,pressure,precipitation
0,2010-01-01,18.0,14.0,85.0,5.0,29.91,23.0
1,2010-01-02,18.0,16.0,89.0,6.0,29.94,28.8
2,2010-01-03,18.0,14.0,82.0,10.0,29.94,2.5
3,2010-01-04,18.0,13.0,76.0,9.0,29.94,1.7
4,2010-01-05,19.0,12.0,69.0,10.0,29.91,1.3